server {
    listen 80;
    listen [::]:80;
    server_name jotoglobal.com www.jotoglobal.com;

    root /var/www/jotoglobal/current;
    index index.html;
    client_max_body_size 16k;
    access_log /var/log/nginx/jotoglobal.access.log;
    error_log /var/log/nginx/jotoglobal.error.log;

    include /etc/nginx/snippets/jotoglobal-security-headers.conf;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    include /etc/nginx/snippets/jotoglobal-locations.conf;
}
