server {
    listen 80;
    listen [::]:80;
    server_name jotoglobal.com www.jotoglobal.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 301 https://jotoglobal.com$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name jotoglobal.com;

    ssl_certificate /etc/letsencrypt/live/jotoglobal.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jotoglobal.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/jotoglobal/current;
    index index.html;
    client_max_body_size 16k;
    access_log /var/log/nginx/jotoglobal.access.log;
    error_log /var/log/nginx/jotoglobal.error.log;

    include /etc/nginx/snippets/jotoglobal-security-headers.conf;
    include /etc/nginx/snippets/jotoglobal-locations.conf;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.jotoglobal.com;

    ssl_certificate /etc/letsencrypt/live/jotoglobal.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jotoglobal.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://jotoglobal.com$request_uri;
}
