from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text()


def test_docker_contract() -> None:
    compose = read("compose.yaml")
    web_dockerfile = read("joto-site-v2/Dockerfile")
    contact_dockerfile = read("joto-site-v2/functions/contact/Dockerfile")
    root_dockerfile = read("Dockerfile.archive")
    requirements = read("requirements.lock")

    assert "name: joto-sunny" in compose
    assert '"127.0.0.1:5173:5173"' in compose
    assert '"127.0.0.1:9000:9000"' in compose
    assert "network_mode: host" not in compose
    assert "profiles:" in compose and "tools" in compose
    assert web_dockerfile.startswith("FROM node:24.18.0-bookworm-slim\n")
    assert contact_dockerfile.startswith("FROM node:24.18.0-bookworm-slim\n")
    assert root_dockerfile.startswith("FROM python:3.12.13-slim-bookworm\n")
    assert requirements.startswith("#\n# This file is autogenerated by pip-compile")


if __name__ == "__main__":
    test_docker_contract()
